# Generated by Django 5.2.1 on 2026-07-04 10:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carmake",
            options={
                "ordering": ["name"],
                "verbose_name": "Car Make",
                "verbose_name_plural": "Car Makes",
            },
        ),
        migrations.AlterModelOptions(
            name="carmodel",
            options={
                "ordering": ["car_make__name", "name"],
                "verbose_name": "Car Model",
                "verbose_name_plural": "Car Models",
            },
        ),
        migrations.AddField(
            model_name="carmake",
            name="country_of_origin",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="carmake",
            name="founded_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carmake",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="carmake",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="car_make",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="djangoapp.carmake",
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("SEDAN", "Sedan"),
                    ("SUV", "SUV"),
                    ("WAGON", "Wagon"),
                    ("COUPE", "Coupe"),
                    ("HATCHBACK", "Hatchback"),
                    ("TRUCK", "Truck"),
                    ("MINIVAN", "Minivan"),
                    ("CONVERTIBLE", "Convertible"),
                ],
                default="SUV",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="year",
            field=models.IntegerField(
                default=2024,
                validators=[
                    django.core.validators.MaxValueValidator(2026),
                    django.core.validators.MinValueValidator(2015),
                ],
            ),
        ),
    ]
