# Generated by Django 4.2.7 on 2026-07-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_carmake_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealershipBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField(unique=True)),
                ('lead_credits', models.IntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Dealership Billing',
                'verbose_name_plural': 'Dealership Billings',
            },
        ),
    ]
