# Generated by Django 4.2.7 on 2026-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_dealershipbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershipbilling',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealershipbilling',
            name='sponsor_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
