# Generated by Django 4.2.7 on 2026-07-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_dealershipbilling_is_sponsored_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dealer_id', models.IntegerField(blank=True, null=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
